### ISSUE TITLE
Can't run Backend Redbus

### ISSUE THREAD

**Issue by airlangga2377** [nitansh11/redbus#34]
MongoParseError: options usecreateindex, usefindandmodify are not supported
    at parseOptions (C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongodb\lib\connection_string.js:290:15)
    at new MongoClient (C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongodb\lib\mongo_client.js:64:63)
    at C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongoose\lib\connection.js:801:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongoose\lib\connection.js:798:19)       
    at C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongoose\lib\index.js:380:10
    at C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\Intel\Downloads\redbus\back-end-redbus\node_modules\mongoose\lib\index.js:1225:10) {
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by rohity20** [comment]
We can modify the code for connecting the server with the backend i.e connect function as :
const connect = () => {
  const db = mongoose.connection; 

  db.on('error', (error) => {
    console.error('MongoDB connection error:', error);
  });

  db.once('open', () => {
    console.log('MongoDB connection established.');
  });

  return mongoose.connect(
    "mongodb+srv://redbus_db_user_1:umJkhSujb8dZoc2a@redbuscnstructweek.bujg6.mongodb.net/redbus?retryWrites=true&w=majority",
    {
      useCreateIndex: true,
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useFindAndModify: false,
    }
  );
};
These changes allow you to handle MongoDB connection events correctly and avoid the errors related to listening to events on the Db class.
